# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hangman_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(719, 593)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(719, 586))
        MainWindow.setStyleSheet("background-color: rgb(231, 234, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_forca = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_forca.sizePolicy().hasHeightForWidth())
        self.label_forca.setSizePolicy(sizePolicy)
        self.label_forca.setText("")
        self.label_forca.setTextFormat(QtCore.Qt.PlainText)
        self.label_forca.setPixmap(QtGui.QPixmap("img/draw_forca-0.png"))
        self.label_forca.setScaledContents(True)
        self.label_forca.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forca.setObjectName("label_forca")
        self.gridLayout.addWidget(self.label_forca, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 1)
        self.btNovaPalavra = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btNovaPalavra.sizePolicy().hasHeightForWidth())
        self.btNovaPalavra.setSizePolicy(sizePolicy)
        self.btNovaPalavra.setMinimumSize(QtCore.QSize(200, 0))
        self.btNovaPalavra.setSizeIncrement(QtCore.QSize(100, 0))
        self.btNovaPalavra.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btNovaPalavra.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 32, 100);\n"
"    font: 12pt \"Comic Sans MS\";\n"
"    border: 2px solid;\n"
"    border-color: rgb(2, 29, 102);\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5685, y1:0.006, x2:0.681818, y2:1, stop:0 rgba(144, 191, 225, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton:hover {        \n"
"    background-color: rgb(158, 199, 229);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: qlineargradient(spread:pad, x1:0.518, y1:1, x2:0.523, y2:0.0113636, stop:0 rgba(144, 191, 225, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"    background-color: rgb(231, 234, 255);\n"
"}")
        self.btNovaPalavra.setDefault(False)
        self.btNovaPalavra.setObjectName("btNovaPalavra")
        self.gridLayout.addWidget(self.btNovaPalavra, 11, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_display = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.label_display.sizePolicy().hasHeightForWidth())
        self.label_display.setSizePolicy(sizePolicy)
        self.label_display.setBaseSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_display.setFont(font)
        self.label_display.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_display.setStyleSheet("color: rgb(1, 51, 118);\n"
"font: 75 20pt \"Comic Sans MS\";")
        self.label_display.setText("")
        self.label_display.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_display.setWordWrap(True)
        self.label_display.setObjectName("label_display")
        self.horizontalLayout.addWidget(self.label_display)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btB = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btB.sizePolicy().hasHeightForWidth())
        self.btB.setSizePolicy(sizePolicy)
        self.btB.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btB.setFont(font)
        self.btB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btB.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btB.setObjectName("btB")
        self.gridLayout_2.addWidget(self.btB, 0, 1, 1, 1)
        self.btE = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btE.sizePolicy().hasHeightForWidth())
        self.btE.setSizePolicy(sizePolicy)
        self.btE.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btE.setFont(font)
        self.btE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btE.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btE.setObjectName("btE")
        self.gridLayout_2.addWidget(self.btE, 0, 4, 1, 1)
        self.btF = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btF.sizePolicy().hasHeightForWidth())
        self.btF.setSizePolicy(sizePolicy)
        self.btF.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btF.setFont(font)
        self.btF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btF.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btF.setObjectName("btF")
        self.gridLayout_2.addWidget(self.btF, 0, 5, 1, 1)
        self.btG = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btG.sizePolicy().hasHeightForWidth())
        self.btG.setSizePolicy(sizePolicy)
        self.btG.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btG.setFont(font)
        self.btG.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btG.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btG.setObjectName("btG")
        self.gridLayout_2.addWidget(self.btG, 0, 6, 1, 1)
        self.btH = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btH.sizePolicy().hasHeightForWidth())
        self.btH.setSizePolicy(sizePolicy)
        self.btH.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btH.setFont(font)
        self.btH.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btH.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btH.setObjectName("btH")
        self.gridLayout_2.addWidget(self.btH, 0, 7, 1, 1)
        self.btI = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btI.sizePolicy().hasHeightForWidth())
        self.btI.setSizePolicy(sizePolicy)
        self.btI.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btI.setFont(font)
        self.btI.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btI.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btI.setObjectName("btI")
        self.gridLayout_2.addWidget(self.btI, 0, 8, 1, 1)
        self.btJ = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btJ.sizePolicy().hasHeightForWidth())
        self.btJ.setSizePolicy(sizePolicy)
        self.btJ.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btJ.setFont(font)
        self.btJ.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btJ.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btJ.setObjectName("btJ")
        self.gridLayout_2.addWidget(self.btJ, 1, 0, 1, 1)
        self.btC = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btC.sizePolicy().hasHeightForWidth())
        self.btC.setSizePolicy(sizePolicy)
        self.btC.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btC.setFont(font)
        self.btC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btC.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btC.setObjectName("btC")
        self.gridLayout_2.addWidget(self.btC, 0, 2, 1, 1)
        self.btD = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btD.sizePolicy().hasHeightForWidth())
        self.btD.setSizePolicy(sizePolicy)
        self.btD.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btD.setFont(font)
        self.btD.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btD.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btD.setObjectName("btD")
        self.gridLayout_2.addWidget(self.btD, 0, 3, 1, 1)
        self.btK = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btK.sizePolicy().hasHeightForWidth())
        self.btK.setSizePolicy(sizePolicy)
        self.btK.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btK.setFont(font)
        self.btK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btK.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btK.setObjectName("btK")
        self.gridLayout_2.addWidget(self.btK, 1, 1, 1, 1)
        self.btM = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btM.sizePolicy().hasHeightForWidth())
        self.btM.setSizePolicy(sizePolicy)
        self.btM.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btM.setFont(font)
        self.btM.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btM.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btM.setObjectName("btM")
        self.gridLayout_2.addWidget(self.btM, 1, 3, 1, 1)
        self.btN = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btN.sizePolicy().hasHeightForWidth())
        self.btN.setSizePolicy(sizePolicy)
        self.btN.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btN.setFont(font)
        self.btN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btN.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btN.setObjectName("btN")
        self.gridLayout_2.addWidget(self.btN, 1, 4, 1, 1)
        self.btO = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btO.sizePolicy().hasHeightForWidth())
        self.btO.setSizePolicy(sizePolicy)
        self.btO.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btO.setFont(font)
        self.btO.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btO.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btO.setObjectName("btO")
        self.gridLayout_2.addWidget(self.btO, 1, 5, 1, 1)
        self.btP = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btP.sizePolicy().hasHeightForWidth())
        self.btP.setSizePolicy(sizePolicy)
        self.btP.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btP.setFont(font)
        self.btP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btP.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btP.setObjectName("btP")
        self.gridLayout_2.addWidget(self.btP, 1, 6, 1, 1)
        self.btR = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btR.sizePolicy().hasHeightForWidth())
        self.btR.setSizePolicy(sizePolicy)
        self.btR.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btR.setFont(font)
        self.btR.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btR.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btR.setObjectName("btR")
        self.gridLayout_2.addWidget(self.btR, 1, 8, 1, 1)
        self.btQ = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btQ.sizePolicy().hasHeightForWidth())
        self.btQ.setSizePolicy(sizePolicy)
        self.btQ.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btQ.setFont(font)
        self.btQ.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btQ.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btQ.setObjectName("btQ")
        self.gridLayout_2.addWidget(self.btQ, 1, 7, 1, 1)
        self.btL = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btL.sizePolicy().hasHeightForWidth())
        self.btL.setSizePolicy(sizePolicy)
        self.btL.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btL.setFont(font)
        self.btL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btL.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btL.setObjectName("btL")
        self.gridLayout_2.addWidget(self.btL, 1, 2, 1, 1)
        self.btS = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btS.sizePolicy().hasHeightForWidth())
        self.btS.setSizePolicy(sizePolicy)
        self.btS.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btS.setFont(font)
        self.btS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btS.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btS.setObjectName("btS")
        self.gridLayout_2.addWidget(self.btS, 2, 0, 1, 1)
        self.btT = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btT.sizePolicy().hasHeightForWidth())
        self.btT.setSizePolicy(sizePolicy)
        self.btT.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btT.setFont(font)
        self.btT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btT.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btT.setObjectName("btT")
        self.gridLayout_2.addWidget(self.btT, 2, 1, 1, 1)
        self.btU = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btU.sizePolicy().hasHeightForWidth())
        self.btU.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btU.setFont(font)
        self.btU.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btU.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btU.setObjectName("btU")
        self.gridLayout_2.addWidget(self.btU, 2, 2, 1, 1)
        self.btV = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btV.sizePolicy().hasHeightForWidth())
        self.btV.setSizePolicy(sizePolicy)
        self.btV.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btV.setFont(font)
        self.btV.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btV.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btV.setObjectName("btV")
        self.gridLayout_2.addWidget(self.btV, 2, 3, 1, 1)
        self.btW = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btW.sizePolicy().hasHeightForWidth())
        self.btW.setSizePolicy(sizePolicy)
        self.btW.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btW.setFont(font)
        self.btW.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btW.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btW.setObjectName("btW")
        self.gridLayout_2.addWidget(self.btW, 2, 4, 1, 1)
        self.btX = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btX.sizePolicy().hasHeightForWidth())
        self.btX.setSizePolicy(sizePolicy)
        self.btX.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btX.setFont(font)
        self.btX.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btX.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btX.setObjectName("btX")
        self.gridLayout_2.addWidget(self.btX, 2, 5, 1, 1)
        self.btY = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btY.sizePolicy().hasHeightForWidth())
        self.btY.setSizePolicy(sizePolicy)
        self.btY.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btY.setFont(font)
        self.btY.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btY.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btY.setObjectName("btY")
        self.gridLayout_2.addWidget(self.btY, 2, 6, 1, 1)
        self.btZ = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btZ.sizePolicy().hasHeightForWidth())
        self.btZ.setSizePolicy(sizePolicy)
        self.btZ.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btZ.setFont(font)
        self.btZ.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btZ.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}\n"
"")
        self.btZ.setObjectName("btZ")
        self.gridLayout_2.addWidget(self.btZ, 2, 7, 1, 1)
        self.btA = QtWidgets.QPushButton(self.centralwidget)
        self.btA.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btA.sizePolicy().hasHeightForWidth())
        self.btA.setSizePolicy(sizePolicy)
        self.btA.setMinimumSize(QtCore.QSize(33, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btA.setFont(font)
        self.btA.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btA.setMouseTracking(False)
        self.btA.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 24, 102);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Comic Sans MS\";\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(1, 51, 118);\n"
"    background-color: rgb(184, 214, 236);\n"
"    border: 2px solid rgb(1, 51, 118);\n"
"}")
        self.btA.setObjectName("btA")
        self.gridLayout_2.addWidget(self.btA, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 11, 2, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 22, 95);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_lives = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_lives.setFont(font)
        self.label_lives.setStyleSheet("color: rgb(0, 24, 101);")
        self.label_lives.setObjectName("label_lives")
        self.verticalLayout.addWidget(self.label_lives, 0, QtCore.Qt.AlignHCenter)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.label_guessed = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_guessed.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_guessed.setFont(font)
        self.label_guessed.setStyleSheet("color: rgb(255, 0, 0);\n"
"border: 2px solid rgb(0, 24, 102);")
        self.label_guessed.setText("")
        self.label_guessed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_guessed.setWordWrap(True)
        self.label_guessed.setObjectName("label_guessed")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_guessed)
        self.gridLayout.addLayout(self.formLayout, 0, 2, 1, 1)
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logo.sizePolicy().hasHeightForWidth())
        self.label_logo.setSizePolicy(sizePolicy)
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("img/logo_forca_dark.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.gridLayout.addWidget(self.label_logo, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Chute uma letra:"))
        self.btNovaPalavra.setText(_translate("MainWindow", "Nova Palavra"))
        self.btB.setText(_translate("MainWindow", "B"))
        self.btE.setText(_translate("MainWindow", "E"))
        self.btF.setText(_translate("MainWindow", "F"))
        self.btG.setText(_translate("MainWindow", "G"))
        self.btH.setText(_translate("MainWindow", "H"))
        self.btI.setText(_translate("MainWindow", "I"))
        self.btJ.setText(_translate("MainWindow", "J"))
        self.btC.setText(_translate("MainWindow", "C"))
        self.btD.setText(_translate("MainWindow", "D"))
        self.btK.setText(_translate("MainWindow", "K"))
        self.btM.setText(_translate("MainWindow", "M"))
        self.btN.setText(_translate("MainWindow", "N"))
        self.btO.setText(_translate("MainWindow", "O"))
        self.btP.setText(_translate("MainWindow", "P"))
        self.btR.setText(_translate("MainWindow", "R"))
        self.btQ.setText(_translate("MainWindow", "Q"))
        self.btL.setText(_translate("MainWindow", "L"))
        self.btS.setText(_translate("MainWindow", "S"))
        self.btT.setText(_translate("MainWindow", "T"))
        self.btU.setText(_translate("MainWindow", "U"))
        self.btV.setText(_translate("MainWindow", "V"))
        self.btW.setText(_translate("MainWindow", "W"))
        self.btX.setText(_translate("MainWindow", "X"))
        self.btY.setText(_translate("MainWindow", "Y"))
        self.btZ.setText(_translate("MainWindow", "Z"))
        self.btA.setText(_translate("MainWindow", "A"))
        self.label_2.setText(_translate("MainWindow", "Vidas:"))
        self.label_lives.setText(_translate("MainWindow", "6"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
